import React, { Fragment } from "react";
import type { AppProps } from "next/app";
import Head from "next/head";
import "@/styles/globals.css";

function App({ Component, pageProps }: AppProps) {
  return (
    <Fragment>
      <Head>
        <title>Portfolio</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Fragment>
  );
}

export default App;
